name: Manual
on:
  workflow_dispatch:
    inputs:
      greeting:
        type: string
        default: Hello
        required: true
        description: Acheerful word
jobs:
  run:
    steps:
      - run: echo "${{ inputs.greeting }}"